@startuml




component {
interface a
interface b
interface c
interface d
interface e <<M>>
interface g <<M>>
interface h <<M>>
interface j
interface m
interface n
interface o
}


b ---> a
a --> m
m -l-> b

c -u-> m
b --> c

n -u-> o
b --> n
o -r--> b

a -d-> d
d -d-> e
d --> g
d --> j
b --> h
j -r-> h
j --> b

skinparam interface {
backgroundColor<<M>> RosyBrown
}

@enduml
